# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       vumeter

# >> macros
# << macros

Summary:    VUMeter -- A Simplistic VU-Meter
Version:    0.2.1
Release:    1
Group:      Applications/Multimedia
License:    GPLv3
URL:        http://vumeter.garage.maemo.org/
Source0:    %{name}_%{version}.tar.gz
Source100:  vumeter.yaml
BuildRequires:  pkgconfig(QtCore) >= 4.7.0
BuildRequires:  pkgconfig(QtGui)
BuildRequires:  pkgconfig(qdeclarative-boostable)
BuildRequires:  pkgconfig(libpulse)
BuildRequires:  pkgconfig(libpulse-simple)
BuildRequires:  desktop-file-utils

%description
VUMeter is a fun-tool to display the sound level. VUMeter presents the current sound level using different views.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_datadir}/applications/%{name}.desktop
/opt/%{name}
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files
